// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6znT4zOuAcWN7R70PlKnEjymLcVxRA0c',
    appId: '1:899409460852:web:1ac4777a3029439b109b21',
    messagingSenderId: '899409460852',
    projectId: 'testapp-fb888',
    authDomain: 'testapp-fb888.firebaseapp.com',
    storageBucket: 'testapp-fb888.firebasestorage.app',
    measurementId: 'G-0R5EVXPY04',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeV56StBEmEwSo55y9szjvH3-oPjTZbc0',
    appId: '1:899409460852:android:14f1d4fac69f9173109b21',
    messagingSenderId: '899409460852',
    projectId: 'testapp-fb888',
    storageBucket: 'testapp-fb888.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCruEtE0fYeqiRsTglcIaNKUXnoVn6JhgQ',
    appId: '1:899409460852:ios:ecb1baad1406c5ad109b21',
    messagingSenderId: '899409460852',
    projectId: 'testapp-fb888',
    storageBucket: 'testapp-fb888.firebasestorage.app',
    iosClientId: '899409460852-5a27u9nnn0dje4fif1gdpals4vr27ou3.apps.googleusercontent.com',
    iosBundleId: 'com.example.carwanDough',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCruEtE0fYeqiRsTglcIaNKUXnoVn6JhgQ',
    appId: '1:899409460852:ios:ecb1baad1406c5ad109b21',
    messagingSenderId: '899409460852',
    projectId: 'testapp-fb888',
    storageBucket: 'testapp-fb888.firebasestorage.app',
    iosClientId: '899409460852-5a27u9nnn0dje4fif1gdpals4vr27ou3.apps.googleusercontent.com',
    iosBundleId: 'com.example.carwanDough',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtZRLJuKZeO9LPhpmaSqE7uooVmuo6CP8',
    appId: '1:899409460852:web:68920ed7145db905109b21',
    messagingSenderId: '899409460852',
    projectId: 'testapp-fb888',
    authDomain: 'testapp-fb888.firebaseapp.com',
    storageBucket: 'testapp-fb888.firebasestorage.app',
    measurementId: 'G-JQJL349ESB',
  );
}
